hackthon/apps/profiles/urls.py
#-*- coding: utf-8 -*-

from django.conf.urls import patterns, url

from profiles import views


urlpatterns = patterns('',
    url(r'^(?P<pk>\d+)/edit/$', views.ProfileEditView.as_view(),
                        name='profile_edit'),
    url(r'^list/$', views.ProifileList.as_view(),
                        name='profile_list'),
    url(r'^register/$', views.register,
                        name='profiles_register'),
    url(r'^register/sponsorship/$', views.sponsorship_register,
                        name='sponsorship_register'),
    url(r'^(?P<pk>\d+)/$', views.ProifileDetail.as_view(),
                        name='profile_detail'),

    url(r'^projects/list/$', views.ProjectList.as_view(),
                        name='project_list'),
    url(r'^projects/create/$', views.ProjectCreateView.as_view(),
                        name='project_create'),
    url(r'^projects/join/$', views.JoinProjectView.as_view(),
                        name='project_left'),
    url(r'^projects/left/$', views.LeftProjectView.as_view(),
                        name='project_join'),
    url(r'^projects/confirm/$', views.ConfirmRegisterView.as_view(),
                        name='project_confirm'),
    url(r'^projects/(?P<pk>\d+)/edit/$', views.ProjectEditView.as_view(),
                        name='project_edit'),
    url(r'^projects/(?P<pk>\d+)/$', views.ProjectDetail.as_view(),
                        name='project_detail'),
    url(r'^messages/$', views.messages_new,
                        name='messages'),
    url(r'^messages/zaebeezaebee/(?P<id>\d+)$', views.messages_zaebee,
                        name='messages_zaebee'),
)

hackthon/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.views.generic import TemplateView, RedirectView

from django.shortcuts import redirect
from django.contrib import admin
from django.contrib.auth import views as auth_views
admin.autodiscover()


urlpatterns = patterns('',
    (r'^admin/', include(admin.site.urls)),
)

#reg urls
urlpatterns += patterns('',
    url(r'^projects/$', RedirectView.as_view(url='/accounts/projects/list/')),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^password/change/$',
        auth_views.password_change,
        name='auth_password_change'),
    url(r'^password/change/done/$',
        auth_views.password_change_done,
        name='auth_password_change_done'),
    url(r'^password/reset/$',
        auth_views.password_reset,
        name='auth_password_reset'),
    url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.password_reset_confirm,
        name='auth_password_reset_confirm'),
    url(r'^password/reset/complete/$',
        auth_views.password_reset_complete,
        name='auth_password_reset_complete'),
    url(r'^password/reset/done/$',
        auth_views.password_reset_done,
        name='auth_password_reset_done'),
)

urlpatterns += patterns('',
    #(r'^$', TemplateView.as_view(template_name="default.html")),
    (r'^$', TemplateView.as_view(template_name="new.html")),
    (r'^first/$', TemplateView.as_view(template_name="first.html")),
    (r'^second/$', TemplateView.as_view(template_name="second.html")),
    (r'^accounts/', include('profiles.urls')),
    (r'^validate/', include('ajax_validation.urls')),
)

urlpatterns += (
    url(r'^static/(?P<path>.*)', 'django.views.static.serve', {'document_root':settings.STATIC_ROOT,'show_indexes': True}),
)

if settings.DEBUG:
    urlpatterns += (
        url(r'^static/(?P<path>.*)', 'django.views.static.serve', {'document_root':settings.STATIC_ROOT,'show_indexes': True}),
        url(r'^media/(?P<path>.*)', 'django.views.static.serve', {'document_root':settings.MEDIA_ROOT,'show_indexes': True}),
    )

hackthon/apps/profiles/models.py
# -*- coding: utf-8 -*-

from django.contrib.auth.models import User
from django.db import models

from django.utils.translation import ugettext_lazy as _


USER_ROLES = (
    ('programmer', u'Программист'),
    ('designer', u'Дизайнер'),
    ('manager', u'Менеджер'),
    ('student', u'Студент'),
    ('other', u'Другое'),
)


class SponsorProfile(models.Model):

    sponsor_email = models.EmailField(_('email'), max_length=75)

    def __unicode__(self):
        return self.sponsor_email


class UserProfile(models.Model):
    user = models.OneToOneField(User,
                        verbose_name=_('user'),
                        unique=True,
                        related_name='profile',)
    avatar = models.CharField(_('Avatar'), max_length=80,
                              blank=True, null=True)
    username = models.CharField(_('Username'), max_length=100)
    user_skills = models.TextField(_('User skills'))
    user_role = models.CharField(_('User role'), max_length=30,
                           choices=USER_ROLES)
    contact = models.CharField(_('Contact'), max_length=40, null=True)
    phone = models.CharField(_('Phone'), max_length=40, blank=True, null=True)
    has_idea = models.BooleanField(_('Has idea'), default=False)
    text_idea = models.TextField(_('Text idea'), blank=True, null=True)
    project = models.ForeignKey('UserProject', verbose_name=_('project'),
                               related_name=_('members'),
                               blank=True, null=True)
    confirmed = models.BooleanField('Confirmed', default=False)

    class Meta:
        verbose_name = _('Profile')
        verbose_name_plural = _('Profiles')

    def __unicode__(self):
        return self.user.username

    @property
    def in_team(self):
        try:
            team =  self.project or self.group
        except:
            return False
        if team:
            return True

    @property
    def team(self):
        if self.in_team:
            return self.project if self.project else self.group

    @property
    def empty(self):
        if self.username and self.user_skills and self.contact:
            return False
        return True

    @property
    def can_join(self):
        if not self.empty and not self.team:
            return True
        return False

    @property
    def can_left(self):
        if not self.empty and self.team.owner != self:
            return True
        return False

    @models.permalink
    def get_absolute_url(self):
        return ('profile_detail', None, {'pk':str(self.pk)})


class UserProject(models.Model):
    created = models.DateTimeField(_('Created'), auto_now=True)
    owner = models.OneToOneField(UserProfile,
                        verbose_name=_('owner'),
                        unique=True,
                        related_name='group',
                        blank=True,null=True,
                        default='')
    avatar = models.CharField(_('Avatar'), max_length=80,
                              blank=True, null=True)
    title = models.CharField(_('Title'), max_length=100)
    text_idea = models.TextField(_('Text idea'), blank=True, null=True)
    require = models.CharField(_('Require staff'), max_length=350, blank=True, null=True)
    is_full = models.BooleanField(_('Is full'), default=False)
    pirvate = models.BooleanField(_('Private'), default=False)
    archived = models.BooleanField(_('Archived'), default=False)

    class Meta:
        verbose_name = _('Project')
        verbose_name_plural = _('Projects')
        ordering = ('-created',)

    def __unicode__(self):
        return '%s - %s' % (self.owner, self.title)

    @models.permalink
    def get_absolute_url(self):
        return ('project_detail', None, {'pk':str(self.pk)})


class Message(models.Model):
    created = models.DateTimeField(_('Created'), auto_now=True)
    text = models.TextField(_('Message'))
    title = models.CharField(_('Title'), max_length=255, null=True, blank=True)

    class Meta:
        verbose_name = _('Message')
        verbose_name_plural = _('Messages')
        ordering = ('-created',)

    def __unicode__(self):
        if self.title:
            return u'%s' % self.title
        else:
            return ''


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profile, created = UserProfile.objects.get_or_create(user=instance)

models.signals.post_save.connect(create_user_profile, sender=User)

hackthon/apps/profiles/forms.py
#-*- coding: utf-8 -*-

from django import forms
from django.conf import settings
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from models import UserProfile, SponsorProfile, UserProject
from utils import clear_email


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        exclude = ('user', 'avatar') # User will be filled in by the view.


class UserProjectForm(forms.ModelForm):

    class Meta:
        model = UserProject
        exclude = ('owner', 'archived', 'avatar') # User will be filled in by the view.



# I put this on all required fields, because it's easier to pick up
# on them with CSS or JavaScript if they have a class of "required"
# in the HTML. Your mileage may vary. If/when Django ticket #3515
# lands in trunk, this will no longer be necessary.
attrs_dict = {'class': 'required'}


class RegistrationForm(forms.Form):
    """
    Form for registering a new user account.

    Validates that the requested username is not already in use, and
    requires the password to be entered twice to catch typos.

    Subclasses should feel free to add any additional validation they
    need, but should avoid defining a ``save()`` method -- the actual
    saving of collected user data is delegated to the active
    registration backend.

    """
    username = forms.RegexField(regex=r'^\w+$',
                                max_length=30,
                                widget=forms.TextInput(attrs=attrs_dict),
                                label=_("Username"),
                                error_messages={'invalid': _("This value must contain only letters, numbers and underscores.")})
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(attrs_dict,
                                                               max_length=75)),
                             label=_("Email address"))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs=attrs_dict, render_value=False),
                                label=_("Password"))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs=attrs_dict, render_value=False),
                                label=_("Password (again)"))

    def clean_username(self):
        """
        Validate that the username is alphanumeric and is not already
        in use.

        """
        try:
            user = User.objects.get(username__iexact=self.cleaned_data['username'])
        except User.DoesNotExist:
            return self.cleaned_data['username']
        raise forms.ValidationError(_("User with this username already exists."))

    def clean(self):
        """
        Verifiy that the values entered into the two password fields
        match. Note that an error here will end up in
        ``non_field_errors()`` because it doesn't apply to a single
        field.

        """
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(_("Password does not match."))
        return self.cleaned_data


class RegistrationFormUniqueEmail(forms.Form):
    """
    Subclass of ``RegistrationForm`` which enforces uniqueness of
    email addresses.

    """
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(attrs_dict,
                                                    maxlength=75)),
                                                    label=_("Email address"))
    password = forms.CharField(widget=forms.PasswordInput(attrs=attrs_dict, render_value=False),
                                label=_("Password"))

    def clean_email(self):
        """
        Validate that the supplied email address is unique for the
        site.

        """
        email = self.cleaned_data['email']
        if User.objects.filter(email__iexact=clear_email(email)).exists():
            raise forms.ValidationError(u"Такой email уже есть. Укажите, пожалуйста, другой адрес.")
        return email


class SponsorshipForm(forms.ModelForm):

    class Meta:
        model = SponsorProfile

    def clean_email(self):
        return email

hackthon/apps/profiles/templates/profiles/base.html
{% extends 'default.html' %}
{% load i18n %}

{% block pagetitle %}
{% endblock %}

{% block info %}
{% endblock %}

{% block register %}
{% endblock %}

{% block sponsors %}
{% endblock %}

{% block additional %}
{% endblock %}

{% block sidebar %}
  <div class="large-4 columns">
    {# include 'includes/_vk.html' #}
    <script type="text/javascript" src="//vk.com/js/api/openapi.js?87"></script>

    <!-- VK Widget -->
    <div id="vk_groups"></div>
    <script type="text/javascript">
      VK.Widgets.Group("vk_groups", {mode: 2, width: "300", height: "290"}, 51121552);
    </script>

    <h4 style="margin-top:30px;">Твиты #hackpoint_che</h4>
    {% include 'includes/_twitter.html' %}
  </div>
{% endblock %}

{% block main %}{% endblock %}

hackthon/apps/profiles/templates/profiles/create_project.html
{% extends "profiles/base.html" %}
{% load i18n widget_tweaks %}

{% block sidebar %}
{% endblock %}

{% block main %}
{{ form.media }}

  <div class="large-8 columns large-centered">

    <ul class="breadcrumbs">
      <li><a href="/">Главная</a></li>
      <li><a href="{% url 'project_list' %}">Проекты</a></li>
      <li class="current"><a href="#">Создать</a></li>
    </ul>

    <form enctype="multipart/form-data" action="." id="form" class="custom form" method="post" novalidate="novalidate">
      <fieldset>
        <legend>Создать проект</legend>
        <p>
        В описании проекта необходимо кратко описать:
        </p>
        <ul>

        <li>проблему, которую вы собираетесь решить;</li>
        <li>ваше решение;</li>
        <li>что вы планируете реализовать за 48 часов;</li>
        <li>кто нужен в команду.</li>
        <hr>
        <p>Обратите внимание, в описании проекта не должно быть кода. Только понятный текст. Описание проекта могут читать другие люди.</p>

        <p>Мы оставляем за собой право изменить проект, если описание не соответствует требованиям.</p>
      {% csrf_token %}
      {{ form.non_field_errors }}

      {{ form.title|append_attr:"placeholder:Краткий заголовок для проекта"|add_error_class:"error" }}
      {{ form.title.errors }}

      {{ form.text_idea|append_attr:"placeholder:Описание вашей идеи. Также укажите, кто требуется вам в команду."|add_error_class:"error" }}
      {{ form.text_idea.errors }}
      <br>

      <input class="button" value="{% trans 'Создать' %}" type="submit">
      </fieldset>
    </form>

  </div>
{% endblock %}

{% block extrajs %}
  <link href="{{ STATIC_URL }}/imperavi/redactor/css/redactor.css" type="text/css" media="all" rel="stylesheet">
  <script src="{{ STATIC_URL }}/imperavi/redactor/langs/ru.js"></script>
  <script src="{{ STATIC_URL }}/imperavi/redactor/redactor.min.js"></script>
  <script type="text/javascript">
    $(document).ready(
    function() {
      $('#id_text_idea').redactor({
      lang:'ru',
      buttons: ['html', '|', 'formatting', '|', 'bold', 'italic', '|', 'unorderedlist', 'orderedlist', '|', 'link']
      });
    });
  </script>
{% endblock %}

hackthon/apps/profiles/templates/profiles/edit_profile.html
{% extends "profiles/base.html" %}
{% load i18n widget_tweaks %}

{% block sidebar %}
{% endblock %}

{% block main %}

  <div class="large-8 columns large-centered">

    <ul class="breadcrumbs">
      <li><a href="/">Главная</a></li>
      <li><a href="{% url 'profile_list' %}">Участники</a></li>
      <li class=""><a href="{% url 'profile_detail' user.profile.pk %}">Мой профиль</a></li>
      <li class="current"><a href="#">Редактирование</a></li>
    </ul>

    <div class="form-container clearfix">
      <form enctype="multipart/form-data" action="." id="form" class="form profile-form" method="post" novalidate="novalidate">
        <fieldset>
          <legend>Редактировать аккаунт</legend>
        {% csrf_token %}
        {{ form.non_field_errors }}
        {{ form.username|append_attr:"placeholder:Ваш юзернейм или реальное имя"|add_error_class:"error" }}
        {{ form.username.errors }}

        {{ form.user_skills|append_attr:"placeholder:Ваши навыки или технологии, которыми владеете"|add_error_class:"error" }}
        {{ form.user_skills.errors }}

        {{ form.user_role }}
        {{ form.user_role.errors }}

        {{ form.contact|append_attr:"placeholder:Ссылка на ваш профиль, skype, чтобы участники команды смогли с вами связаться"|add_error_class:"error" }}
        {{ form.contact.errors }}

        {{ form.phone|append_attr:"placeholder:Ваш телефон. Например, +7 987 654 4321 (необязательно)"|add_error_class:"error" }}
        {{ form.phone.errors }}

        <label for="id_has_idea">{{ form.has_idea }}&nbsp;У меня есть идея</label>
        {{ form.has_idea.errors }}

        {{ form.text_idea|append_attr:"placeholder:Краткое описание вашей идеи. Что или кто требуется для ее реализации?"|add_error_class:"error" }}
        {{ form.text_idea.errors }}

        <input class="button" value="{% trans 'Обновить' %}" type="submit">
        </fieldset>
      </form>
    </div>

  </div>
{% endblock %}

hackthon/apps/profiles/templates/profiles/edit_project.html
{% extends "profiles/base.html" %}
{% load i18n widget_tweaks %}

{% block sidebar %}
{% endblock %}

{% block main %}
{{ form.media }}

  <div class="large-8 columns large-centered">

    <ul class="breadcrumbs">
      <li><a href="/">Главная</a></li>
      <li><a href="{% url 'project_list' %}">Проекты</a></li>
      <li class=""><a href="{% url 'project_detail' object.pk %}">{{ object.title }}</a></li>
      <li class="current"><a href="#">Редактирование</a></li>
    </ul>

    <form enctype="multipart/form-data" action="." id="form" class="form" method="post" novalidate="novalidate">
      <fieldset>
        <legend>Редактировать проект</legend>
      {% csrf_token %}
      {{ form.non_field_errors }}

      {{ form.title|append_attr:"placeholder:Краткий заголовок для проекта"|add_error_class:"error" }}
      {{ form.title.errors }}

      {{ form.text_idea|append_attr:"placeholder:Описание вашей идеи. Также укажите, кто требуется вам в команду. Например: \"Нужны в команду:дизайнер, программист, 2 менеждера\""|add_error_class:"error" }}
      {{ form.text_idea.errors }}

      <br>

      <label for="id_is_full">{{ form.is_full }}&nbsp;Команда укомплектована <i>(Участники не смогут присоединиться к вашему проекту)</i></label>
      {{ form.is_full.errors }}
      <br>

      <input class="button" value="{% trans 'Обновить' %}" type="submit">
      </fieldset>
    </form>

  </div>
{% endblock %}

{% block extrajs %}
  <link href="{{ STATIC_URL }}/imperavi/redactor/css/redactor.css" type="text/css" media="all" rel="stylesheet">
  <script src="{{ STATIC_URL }}/imperavi/redactor/langs/ru.js"></script>
  <script src="{{ STATIC_URL }}/imperavi/redactor/redactor.min.js"></script>
  <script type="text/javascript">
    $(document).ready(
    function() {
      $('#id_text_idea').redactor({
      lang:'ru',
      buttons: ['html', '|', 'formatting', '|', 'bold', 'italic', '|', 'unorderedlist', 'orderedlist', '|', 'link']
      });
    });
  </script>
{% endblock %}

hackthon/apps/profiles/templates/profiles/register.html
{% extends 'default.html' %}


{% block content %}
<form class="form" method="POST">
  {% csrf_token %}
  {{ form.errors }}
  {{ form.as_p }}
  <input type="submit" class="button" value="Зарегиться">
</form>
{% endblock %}

hackthon/apps/profiles/templates/profiles/register_confirm.html
{% extends 'default.html' %}

{% block register %}
  <div data-alert="" class="alert-box">
    {{ message }}
    <a href="" class="close">×</a>
  </div>
{% endblock %}

hackthon/apps/profiles/templates/profiles/userprofile_detail.html
{% extends 'profiles/base.html' %}
{% load i18n gravatar markup %}

{% block main %}

  <div class="large-8 columns">

    <ul class="breadcrumbs">
      <li><a href="/">Главная</a></li>
      <li><a href="{% url 'profile_list' %}">Участники</a></li>
      <li class="current"><a href="#">{% ifequal user profile.user %}Мой профиль{% else %}{{ profile.username }}{% endifequal %}</a></li>
    </ul>

    {% if user.profile = profile and not profile.confirmed %}
    <div class="row">
      <div class="small-12 columns">
        <a data-profile-id="{{ profile.pk }}" id="total_confirm" class="small-12 columns button" title="Подтвердить регистрацию" href="{% url 'project_create' %}">Я точно приду</a>
      </div>
    </div>
    {% endif %}

    <div class="row">
      <div class="small-3 columns text-center">
        <a id="user_avatar" class="th" href="#">
          {% if profile.avatar %}
            <img src="{{ profile.avatar }}/convert?w=150&h=150">
          {% else %}
            {% gravatar_img_for_email profile.user.email %}
          {% endif %}
        </a>
        {% ifequal user.profile profile %}
        <input type="filepicker" data-fp-button-text="Изменить аватар" data-fp-apikey="A3lXl09sRSejY4e0pOOSQz" data-fp-mimetypes="image/*" data-fp-container="modal" data-fp-services="COMPUTER,DROPBOX" onchange="setAvatar(event.fpfile.url)" class="button tiny secondary small-12">
        {% endifequal %}

        {% if not user.profile.empty and not user.profile.in_team and user.profile = profile %}
          <a class="button tiny primary small-12" title="Создать проект" href="{% url 'project_create' %}"><i class="foundicon-idea"></i>&nbsp;Создать проект</a>
        {% endif %}

      </div>

      <div class="small-9 columns">
        {% if profile.username %}
        <h4>
          {{ profile.username }}
          {% ifequal user.profile profile %}
            <a class="button tiny secondary" title="Редактировать профиль" href="{% url 'profile_edit' profile.pk %}"><i class="foundicon-edit"></i>&nbsp;Редактировать</a>
          {% endifequal %}
        </h4>
        {% endif %}

        {% if profile.user == user %}
        <p><b>Email:</b> {{ user.email }}</p>
        {% endif %}

        <p><b>Контакты:</b>{% if profile.team and user.profile.team = profile.team or profile.user == user %} {{ profile.contact|default:"" }}{% else %} <i>Видны только членам команды</i>{% endif %}</p>

        <p>
        <b>Навыки:</b>
        {% if profile.user_skills %}
          {{ profile.user_skills }}<br>
        {% else %}
          Не указано<br>
        {% endif %}
        </p>

        <p><b>Роль в команде:</b> {{ profile.get_user_role_display }}<br></p>

        {% if profile.in_team %}
          <p>
            <b>Проект:</b> <a href="{% url 'project_detail' profile.team.pk %}"><i class="foundicon-idea"></i>{{ profile.team.title }}</a><br>
          </p>
        {% endif %}

        {% if profile.has_idea %}
          <p>
            <a class="button tiny secondary" href="#">Есть идея!</a><br>
          </p>
        {% endif %}
          {% if profile.text_idea %}
            {% if user.is_authenticated %}
              <div class="row">
                <div class="large-12 columns">{{ profile.text_idea|markdown:"safe" }}</div>
              </div>
            {% else %}
              <small>Описание доступно только после регистрации</small>
            {% endif %}
          {% endif %}
      </div>
    </div>

  </div>

{% endblock %}

{% block extrajs %}
{% ifequal user.profile profile %}
  <script type="text/javascript" src="//api.filepicker.io/v1/filepicker.js"></script>
  <script type="text/javascript">
    var setAvatar = function(avatarUrl) {
      $.post("{% url 'profile_edit' user.profile.pk %}", {
        avatar: avatarUrl
      })
      .success(function() {
        $('#user_avatar img').attr('src', avatarUrl);
      });

    };
  </script>
{% endifequal %}
{% endblock %}

hackthon/apps/profiles/templates/profiles/userprofile_list.html
{% extends 'profiles/base.html' %}
{% load gravatar pymorphy_tags %}

{% block main %}
  <div class="large-8 columns">

    <ul class="breadcrumbs">
      <li><a href="/">Главная</a></li>
      <li class="current"><a href="#">Участники</a></li>
    </ul>

    {% regroup profile_list by get_user_role_display|inflect:"мн" as profiles %}
    <dl class="user_list">
      {% for profile in profiles %}
      <dt><h4 class="subheader">{{ profile.grouper|default:"Не указано" }} <span class="label">{{ profile.list|length}}</span></h4></dt>
      <hr>
      {% for item in profile.list %}
        <dd>
          <div class="row">
            <div class="small-2 columns">
              <a class="th" href="{% url 'profile_detail' item.pk %}">
                {% if item.avatar %}
                  <img src="{{ item.avatar }}/convert?w=80&h=80">
                {% else %}
                  {% gravatar_img_for_email item.user.email %}
                {% endif %}
              </a>
            </div>

            <div class="small-10 columns">
              <!-- {{ item.get_user_role_display }}<br> -->
              <h6><a class="" href="{% url 'profile_detail' item.pk %}">{{ item.username }}</a></h6>
              {% if item.user_skills %}
                <div class="skills">
                  <b>Навыки:</b>
                  {{ item.user_skills|truncatewords_html:30 }}
                </div>
              {% else %}
                Не указано<br>
              {% endif %}
              {% if item.has_idea and item.text_idea %}
              <a class="button tiny secondary has_idea" href="#">Есть идея!</a>
              <div class="panel hide">
                {{ item.text_idea|safe }}
              </div>
              {% endif %}
              {% if item.team %}
                <a class="button tiny has_project" href="{% url 'project_detail' item.team.pk %}">Есть проект!</a>
              {% endif %}
            </div>
          </div>
          </dd>
        {% endfor %}
      {% endfor %}
    </dl>
  </div>
{% endblock %}

hackthon/apps/profiles/templates/profiles/userproject_list.html
{% extends 'profiles/base.html' %}
{% load gravatar pymorphy_tags %}
{% block pagetitle %}Проекты | Hackpoint'13 Череповец{% endblock %}

{% block main %}
  <div class="large-8 columns">

    <ul class="breadcrumbs">
      <li><a href="/">Главная</a></li>
      <li class="current"><a href="#">Проекты</a></li>
    </ul>

    {% if user.is_authenticated %}
    <div class="large-12 columns">
      <p>Для того, чтобы получить возможность добавить описание своего проекта или присоединиться к понравившемуся вам необходимо <a href="{% url 'profile_edit' user.profile.pk %}">заполнить профиль</a></p>
      {% if not user.profile.in_team and not user.profile.empty %}
      <a class="button" href="{% url 'project_create' %}">Создать проект</a>
      {% endif %}
    </div>
    <hr>
    {% endif %}

    {% for project in project_list %}
    <div class="project_detail">

      <div class="row">
        <div class="large-12 columns">
          <h4><a href="{% url 'project_detail' project.pk %}"><i class="foundicon-idea"></i> {{ project.title }}</a></h4>

          {% if project.avatar %}
          <a class="th" href="{% url 'project_detail' project.pk %}">
            <img src="{{ project.avatar }}/convert?w=600&h=200&crop=10,10,600,200">
          </a>
          {% endif %}

          <div class="subheader">Автор идеи: {{ project.owner.username }}&nbsp;
          </div>
          <div class="subheader">Команда: {% for member in project.members.all %}{{ member.username|default:"Неизвестный" }}{% if not forloop.last %};&nbsp;{% endif %}{% empty %}Пока нет({% endfor %}&nbsp;

            <span class="team_actions">

              {% if not project.is_full %}
              <a style="{% if not user.profile.can_join and not user.profile.team = project %}display:none;{% endif %}" class="button tiny team_join {% ifequal user.profile.team project %}team_joined disabled{% endifequal %}" data-project-id="{{ project.pk }}" data-profile-id="{{ user.profile.pk }}" title="Записаться в команду" href="#">
                <i class="foundicon-checkmark"></i> {% if user.profile.can_join %}Хочу в команду{% endif %}{% ifequal user.profile.team project %}Вы в команде{% endifequal %}
              </a>
              {% endif %}

              <a style="{% if not user.profile.can_left or not user.profile.team = project %}display:none;{% endif %}" class="button tiny secondary team_left" data-project-id="{{ project.pk }}" data-profile-id="{{ user.profile.pk }}" title="Выйти из команды">
                <i class="foundicon-remove"></i> Выйти
              </a>

            </span>

          </div>
        </div>
      </div>

      <div class="row">
        <div class="large-12 columns">
          {{ project.text_idea|default:""|safe|truncatewords_html:20 }}
        </div>
      </div>

    </div>
    {% endfor %}
  </div>
{% endblock %}