hackthon/apps/profiles/urls.py
#-*- coding: utf-8 -*-

from django.conf.urls import patterns, url

from profiles import views


urlpatterns = patterns('',
    url(r'^(?P<pk>\d+)/edit/$', views.ProfileEditView.as_view(),
                        name='profile_edit'),
    url(r'^list/$', views.ProifileList.as_view(),
                        name='profile_list'),
    url(r'^register/$', views.register,
                        name='profiles_register'),
    url(r'^register/sponsorship/$', views.sponsorship_register,
                        name='sponsorship_register'),
    url(r'^(?P<pk>\d+)/$', views.ProifileDetail.as_view(),
                        name='profile_detail'),

    url(r'^projects/list/$', views.ProjectList.as_view(),
                        name='project_list'),
    url(r'^projects/create/$', views.ProjectCreateView.as_view(),
                        name='project_create'),
    url(r'^projects/join/$', views.JoinProjectView.as_view(),
                        name='project_left'),
    url(r'^projects/left/$', views.LeftProjectView.as_view(),
                        name='project_join'),
    url(r'^projects/confirm/$', views.ConfirmRegisterView.as_view(),
                        name='project_confirm'),
    url(r'^projects/(?P<pk>\d+)/edit/$', views.ProjectEditView.as_view(),
                        name='project_edit'),
    url(r'^projects/(?P<pk>\d+)/$', views.ProjectDetail.as_view(),
                        name='project_detail'),
    url(r'^messages/$', views.messages_new,
                        name='messages'),
    url(r'^messages/zaebeezaebee/(?P<id>\d+)$', views.messages_zaebee,
                        name='messages_zaebee'),
)

hackthon/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.views.generic import TemplateView, RedirectView

from django.shortcuts import redirect
from django.contrib import admin
from django.contrib.auth import views as auth_views
admin.autodiscover()


urlpatterns = patterns('',
    (r'^admin/', include(admin.site.urls)),
)

#reg urls
urlpatterns += patterns('',
    url(r'^projects/$', RedirectView.as_view(url='/accounts/projects/list/')),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^password/change/$',
        auth_views.password_change,
        name='auth_password_change'),
    url(r'^password/change/done/$',
        auth_views.password_change_done,
        name='auth_password_change_done'),
    url(r'^password/reset/$',
        auth_views.password_reset,
        name='auth_password_reset'),
    url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.password_reset_confirm,
        name='auth_password_reset_confirm'),
    url(r'^password/reset/complete/$',
        auth_views.password_reset_complete,
        name='auth_password_reset_complete'),
    url(r'^password/reset/done/$',
        auth_views.password_reset_done,
        name='auth_password_reset_done'),
)

urlpatterns += patterns('',
    #(r'^$', TemplateView.as_view(template_name="default.html")),
    (r'^$', TemplateView.as_view(template_name="new.html")),
    (r'^first/$', TemplateView.as_view(template_name="first.html")),
    (r'^second/$', TemplateView.as_view(template_name="second.html")),
    (r'^accounts/', include('profiles.urls')),
    (r'^validate/', include('ajax_validation.urls')),
)

urlpatterns += (
    url(r'^static/(?P<path>.*)', 'django.views.static.serve', {'document_root':settings.STATIC_ROOT,'show_indexes': True}),
)

if settings.DEBUG:
    urlpatterns += (
        url(r'^static/(?P<path>.*)', 'django.views.static.serve', {'document_root':settings.STATIC_ROOT,'show_indexes': True}),
        url(r'^media/(?P<path>.*)', 'django.views.static.serve', {'document_root':settings.MEDIA_ROOT,'show_indexes': True}),
    )

hackthon/apps/profiles/models.py
# -*- coding: utf-8 -*-

from django.contrib.auth.models import User
from django.db import models

from django.utils.translation import ugettext_lazy as _


USER_ROLES = (
    ('programmer', u'Программист'),
    ('designer', u'Дизайнер'),
    ('manager', u'Менеджер'),
    ('student', u'Студент'),
    ('other', u'Другое'),
)


class SponsorProfile(models.Model):

    sponsor_email = models.EmailField(_('email'), max_length=75)

    def __unicode__(self):
        return self.sponsor_email


class UserProfile(models.Model):
    user = models.OneToOneField(User,
                        verbose_name=_('user'),
                        unique=True,
                        related_name='profile',)
    avatar = models.CharField(_('Avatar'), max_length=80,
                              blank=True, null=True)
    username = models.CharField(_('Username'), max_length=100)
    user_skills = models.TextField(_('User skills'))
    user_role = models.CharField(_('User role'), max_length=30,
                           choices=USER_ROLES)
    contact = models.CharField(_('Contact'), max_length=40, null=True)
    phone = models.CharField(_('Phone'), max_length=40, blank=True, null=True)
    has_idea = models.BooleanField(_('Has idea'), default=False)
    text_idea = models.TextField(_('Text idea'), blank=True, null=True)
    project = models.ForeignKey('UserProject', verbose_name=_('project'),
                               related_name=_('members'),
                               blank=True, null=True)
    confirmed = models.BooleanField('Confirmed', default=False)

    class Meta:
        verbose_name = _('Profile')
        verbose_name_plural = _('Profiles')

    def __unicode__(self):
        return self.user.username

    @property
    def in_team(self):
        try:
            team =  self.project or self.group
        except:
            return False
        if team:
            return True

    @property
    def team(self):
        if self.in_team:
            return self.project if self.project else self.group

    @property
    def empty(self):
        if self.username and self.user_skills and self.contact:
            return False
        return True

    @property
    def can_join(self):
        if not self.empty and not self.team:
            return True
        return False

    @property
    def can_left(self):
        if not self.empty and self.team.owner != self:
            return True
        return False

    @models.permalink
    def get_absolute_url(self):
        return ('profile_detail', None, {'pk':str(self.pk)})


class UserProject(models.Model):
    created = models.DateTimeField(_('Created'), auto_now=True)
    owner = models.OneToOneField(UserProfile,
                        verbose_name=_('owner'),
                        unique=True,
                        related_name='group',
                        blank=True,null=True,
                        default='')
    avatar = models.CharField(_('Avatar'), max_length=80,
                              blank=True, null=True)
    title = models.CharField(_('Title'), max_length=100)
    text_idea = models.TextField(_('Text idea'), blank=True, null=True)
    require = models.CharField(_('Require staff'), max_length=350, blank=True, null=True)
    is_full = models.BooleanField(_('Is full'), default=False)
    pirvate = models.BooleanField(_('Private'), default=False)
    archived = models.BooleanField(_('Archived'), default=False)

    class Meta:
        verbose_name = _('Project')
        verbose_name_plural = _('Projects')
        ordering = ('-created',)

    def __unicode__(self):
        return '%s - %s' % (self.owner, self.title)

    @models.permalink
    def get_absolute_url(self):
        return ('project_detail', None, {'pk':str(self.pk)})


class Message(models.Model):
    created = models.DateTimeField(_('Created'), auto_now=True)
    text = models.TextField(_('Message'))
    title = models.CharField(_('Title'), max_length=255, null=True, blank=True)

    class Meta:
        verbose_name = _('Message')
        verbose_name_plural = _('Messages')
        ordering = ('-created',)

    def __unicode__(self):
        if self.title:
            return u'%s' % self.title
        else:
            return ''


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profile, created = UserProfile.objects.get_or_create(user=instance)

models.signals.post_save.connect(create_user_profile, sender=User)

hackthon/apps/profiles/forms.py
#-*- coding: utf-8 -*-

from django import forms
from django.conf import settings
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from models import UserProfile, SponsorProfile, UserProject
from utils import clear_email


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        exclude = ('user', 'avatar') # User will be filled in by the view.


class UserProjectForm(forms.ModelForm):

    class Meta:
        model = UserProject
        exclude = ('owner', 'archived', 'avatar') # User will be filled in by the view.



# I put this on all required fields, because it's easier to pick up
# on them with CSS or JavaScript if they have a class of "required"
# in the HTML. Your mileage may vary. If/when Django ticket #3515
# lands in trunk, this will no longer be necessary.
attrs_dict = {'class': 'required'}


class RegistrationForm(forms.Form):
    """
    Form for registering a new user account.

    Validates that the requested username is not already in use, and
    requires the password to be entered twice to catch typos.

    Subclasses should feel free to add any additional validation they
    need, but should avoid defining a ``save()`` method -- the actual
    saving of collected user data is delegated to the active
    registration backend.

    """
    username = forms.RegexField(regex=r'^\w+$',
                                max_length=30,
                                widget=forms.TextInput(attrs=attrs_dict),
                                label=_("Username"),
                                error_messages={'invalid': _("This value must contain only letters, numbers and underscores.")})
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(attrs_dict,
                                                               max_length=75)),
                             label=_("Email address"))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs=attrs_dict, render_value=False),
                                label=_("Password"))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs=attrs_dict, render_value=False),
                                label=_("Password (again)"))

    def clean_username(self):
        """
        Validate that the username is alphanumeric and is not already
        in use.

        """
        try:
            user = User.objects.get(username__iexact=self.cleaned_data['username'])
        except User.DoesNotExist:
            return self.cleaned_data['username']
        raise forms.ValidationError(_("User with this username already exists."))

    def clean(self):
        """
        Verifiy that the values entered into the two password fields
        match. Note that an error here will end up in
        ``non_field_errors()`` because it doesn't apply to a single
        field.

        """
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(_("Password does not match."))
        return self.cleaned_data


class RegistrationFormUniqueEmail(forms.Form):
    """
    Subclass of ``RegistrationForm`` which enforces uniqueness of
    email addresses.

    """
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(attrs_dict,
                                                    maxlength=75)),
                                                    label=_("Email address"))
    password = forms.CharField(widget=forms.PasswordInput(attrs=attrs_dict, render_value=False),
                                label=_("Password"))

    def clean_email(self):
        """
        Validate that the supplied email address is unique for the
        site.

        """
        email = self.cleaned_data['email']
        if User.objects.filter(email__iexact=clear_email(email)).exists():
            raise forms.ValidationError(u"Такой email уже есть. Укажите, пожалуйста, другой адрес.")
        return email


class SponsorshipForm(forms.ModelForm):

    class Meta:
        model = SponsorProfile

    def clean_email(self):
        return email

hackthon/templates/includes/_map.html
<script type="text/javascript">
  $(document).ready(function() {
    ymaps.ready(init);
    var mainMap, modalMap,
        placeMark;

    function init(){

      var myIconContentLayout = ymaps.templateLayoutFactory.createClass(
      //'<img src="/static/i/hp_placemark.png">'
      '<span style="color:#2e95ec;font-weight:700;font-size:14px;">h</span>'
      );

      mainMap = new ymaps.Map ("map", {
        center: [59.123771, 37.877115],
        zoom: 16,
      });

      modalMap = new ymaps.Map ("map-modal", {
        center: [59.123771, 37.877115],
        zoom: 15,
      });
      modalMap.controls.add("mapTools")
        .add("zoomControl")
        .add("typeSelector");

      placeMark = new ymaps.Placemark([59.123771, 37.877115], {
        content: 'Череповец',
        balloonContent: 'Молодежный центр города Череповца'
        }, {
          iconContentLayout: myIconContentLayout,
        });
      mainMap.geoObjects.add(placeMark);
      placeMark = new ymaps.Placemark([59.123771, 37.877115], {
        content: 'Череповец',
        balloonContent: 'Молодежный центр города Череповца'
        }, {
          iconContentLayout: myIconContentLayout,
        });
      modalMap.geoObjects.add(placeMark);

      ymaps.geoXml.load('http://maps.yandex.ru/export/usermaps/g7mOH573v4EEMY4Sco9BMheLEjapOSSp/').then(function (res) {
      //ymaps.geoXml.load('http://maps.yandex.ru/export/usermaps/T4xMfSgWwncaG8NAU8RRXju-GfAZcTM-/').then(function (res) {
        modalMap.geoObjects.add(res.geoObjects);
      });
    }

  });
</script>

hackthon/templates/includes/_map_modal.html
<div id="mapModal" class="reveal-modal" data-reveal>
  <h4>Полезные места</h4>
  <p>Где можно покушать в нашем городе, купить продуктов или переночевать недалеко от &laquo;Молодежного центра&raquo;</p>
  <p>Доехать до &laquo;Молодежного центра&raquo; от вокзала можно на <b>автобусах №6, №17, №39, №37.</b>
  <a target="_blank" href="http://maps.yandex.ru/?um=g7mOH573v4EEMY4Sco9BMheLEjapOSSp&l=map">Ссылка на карту</a>
  </p>
  <div class="row collapse">
      <div class="large-12 columns">
        <div id="map-modal" style="height:550px;"></div>
      </div>
  </div>
  <a class="close-reveal-modal">&#215;</a>
</div>

hackthon/templates/includes/_metrika.html
<!-- Yandex.Metrika counter -->
  <script type="text/javascript">
    (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
      try {
        w.yaCounter20639434 = new Ya.Metrika({id:20639434,
          clickmap:true,
          trackLinks:true,
          accurateTrackBounce:true});
      } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

      if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
  </script>
  <noscript><div><img src="//mc.yandex.ru/watch/20639434" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

hackthon/templates/includes/_register.html
<div id="registerModal" class="reveal-modal small" data-reveal>
  <h4>Благодарим за регистрацию на hackpoint</h4>
  <p>Заполните форму и в дальнейшем вы сможете точнее подобрать команду и проект для участия.</p>
  <form method="POST" action="{% url 'profiles_register' %}" id="register_full">
    {% csrf_token %}

    <div class="row">
      <input id="id_username" type="text" name="username" value="" placeholder="Меня зовут (никнэйм или реальное имя)" />
    </div>

    <div class="row">
      <input id="id_contact" type="text" name="contact" value="" placeholder="Ссылка на ваш профиль в соц сетях или skype" />
    </div>

    <div class="row">
      <label for="id_user_role">Моя роль в команде</label>
      <select id="id_user_role" class="large" name="user_role">
      <option value="programmer">Программист</option>
      <option value="designer">Дизайнер</option>
      <option value="manager">Менеджер</option>
      <option value="student">Студент</option>
      <option value="other">Другое</option>
      </select>
    </div>

    <div class="row">
      <textarea rows=3 id="id_user_skills" name="user_skills" placeholder="Мои навыки, скилы, умения. Какими технологиями я обладаю."></textarea>
    </div>

    <div class="row">
      <label for="id_has_idea"><input type="checkbox" name="has_idea" id="id_has_idea"> У меня есть идея для проекта</label>
    </div>

    <hr>

    <div class="row">
      <input type="submit" class="button" value="Завершить">
    </div>
  </form>
  <a class="close-reveal-modal">&#215;</a>
</div>

hackthon/templates/includes/_sponsorship.html
<div id="sponsorshipModal" class="reveal-modal small">
  <h4>Спасибо!</h4>
  <p>Мы отправим вам готовый пресс-релиз про hackpoint и спонсорское предложение, на ваш email</p>
  <a class="close-reveal-modal">&#215;</a>
</div>

hackthon/templates/includes/_top_nav.html
{% load activelink gravatar %}
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1>
        <a href="/">
          <img src="{{ STATIC_URL }}i/logo-hp.png">
        </a>
      </h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Меню</span></a></li>
  </ul>

  <section  class="top-bar-section">
    <ul class="right">
      <li class="{% ifstartswith  '/accounts/projects/' %}active{% endifstartswith %}"><a href="{% url 'project_list' %}">Проекты</a></li>
      <li class="{% ifstartswith '/accounts/list/' %}active{% endifstartswith %}"><a href="{% url 'profile_list'%}">Участники</a></li>
      <li data-magellan-arrival="wrapper-register"><a href="/#wrapper-register">Место</a></li>
      <li><a href="/#who">Для кого</a></li>
      <li><a href="/#team-hp">О нас</a></li>
      <li class="divider"></li>
      {% if user.is_authenticated %}
        <li class="has-dropdown profile-menu">
          {% if user.profile.avatar %}
            <a href="{% url 'profile_detail' user.profile.pk %}">
              <img src="{{ user.profile.avatar }}/convert?w=25&h=25">
              Профиль
            </a>
          {% else %}
            <a href="{% url 'profile_detail' user.profile.pk %}">
              {% gravatar_img_for_email user.profile.user.email 25 %}
              Профиль
            </a>
          {% endif %}

          <ul id="usermenu" class="dropdown">
            <li><a href="{% url 'profile_detail' user.profile.id %}">Инфо обо мне</a></li>
            <li><a href="{% url 'profile_edit' user.profile.id %}">Редактировать профиль</a></li>
            {% if user.profile.team %}
            <li><a href="{% url 'project_detail' user.profile.team.pk %}">Мой проект</a></li>
            {% endif %}
            <li><a href="{% url 'logout' %}">Выйти</a></li>
          </ul>
        </li>
      {% else %}
        <li class="has-form"><a class="button alert" href="/#wrapper-register">Регистрация</a>
        <li><a class="button" href="{% url 'login' %}">Вход</a>
        </li>
      {% endif %}
    </ul>
  </section>
</nav>

hackthon/templates/includes/_twitter.html
<a class="twitter-timeline" href="https://twitter.com/hackpoint_che" data-widget-id="295507396799897601" data-theme="light" data-link-color="#45688e" data-chrome="nofooter noheader noborders"  data-related="hackpoint_che,twitter" data-aria-polite="assertive" width="300" height="300" lang="RU">Tweets by @hackpoint_che</a>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>


<!-- BEGIN: Twitter website widget (http://twitterforweb.com) -->
<!--
<div style="width:300px;font-size:8px;text-align:right;"><script type="text/javascript">
    document.write(unescape("%3Cscript src='http://twitterforweb.com/twitterbox.js?username=hackpoint_che&settings=1,0,3,300,505,f4f4f4,1,ffffff,101010,1,1,2E95EC' type='text/javascript'%3E%3C/script%3E"));</script>Created by: <a href="http://twitterforweb.com" target="_blank">twitter website widget</a></div>
-->
<!-- END: Twitter website widget (http://twitterforweb.com) -->

hackthon/templates/includes/_vk.html
<script type="text/javascript" src="//vk.com/js/api/openapi.js?78"></script>
<!-- VK Widget -->
<div id="vk_groups"></div>
<script type="text/javascript">
  VK.Widgets.Group("vk_groups", {
    mode: 0,
    width: "300",
    height: "290"
  }, 51121552);
</script>

hackthon/templates/includes/sponsors.html
<div class="row">
  <div class="large-4 columns">
    <h3 class="text-center">Генеральный партнер</h3>
    <a class="text-center" style="display:block;" rel="nofollow" target="_blank" href="http://www.rusventure.ru/ru">
      <img class="th" id="" src="{{ STATIC_URL }}i/rvk_logo.png" />
    </a>
  </div>

  <div class="large-4 columns">
    <h3 class="text-center">Золотой спонсор</h3>
    <a class="text-center" style="display:block;" rel="nofollow" target="_blank" href="http://www.cmirit.ru/ru/index.html">
      <img class="th" src="{{ STATIC_URL }}i/cmirit_logo.png" />
    </a>
  </div>
  <div class="large-4 columns">
    <h3 class="text-center">Золотой спонсор</h3>
    <a class="text-center" style="display:block;" rel="nofollow" target="_blank" href="http://gik35.ru">
      <img class="th" src="{{ STATIC_URL }}i/gik_logo.png" />
    </a>
  </div>
</div><!-- .row -->
<br><br>

<div class="row">
  <div class="large-12 columns">
    <h3 class="text-center">Спонсоры мероприятия</h3>
    <div class="panel">

      <div class="row">
        <div class="large-3 columns">
          <a rel="nofollow" target="_blank" href="http://chermc.ru/">
            <img class="th" id="cmirit_logo" src="{{ STATIC_URL }}i/mc_logo.jpg" />
          </a><br><br>
          <a rel="nofollow" target="_blank" href="http://ka35.ru/">
            <img class="th" id="ka_logo" src="{{ STATIC_URL }}i/ka_logo.png" />
          </a><br><br>
          <a rel="nofollow" target="_blank" href="http://полиграфическаямастерская.рф" class="">
            <img class="th" id="pm_logo" src="{{ STATIC_URL }}i/pm_logo_.png" />
          </a><br><br>
        </div>
        <div class="large-3 columns">
          <a rel="nofollow" target="_blank" href="http://cherepovets.interzet.ru">
            <img class="th" id="" src="{{ STATIC_URL }}i/interzet_logo.png" />
          </a><br><br>
          <a class="" rel="nofollow" target="_blank" href="http://cleverflow.ru">
            <img class="th" id="" src="{{ STATIC_URL }}i/cf_g_logo.png" />
          </a><br><br>
          <a rel="nofollow" target="_blank" href="http://www.iteam24.com" class="">
            <img class="th" id="" src="{{ STATIC_URL }}i/iteam24_logo.png" />
          </a><br><br>
        </div>
        <div class="large-3 columns">
          <a rel="nofollow" target="_blank" href="#">
            <img class="th" id="" src="{{ STATIC_URL }}i/nortis_logo.png" />
          </a><br><br>
          <a class="" rel="nofollow" target="_blank" href="http://imit.ru">
            <img class="th" id="imit_logo" src="{{ STATIC_URL }}i/imit_logo.png" />
          </a><br><br>
          <a class="" rel="nofollow" target="_blank" href="http://igra35.ru">
            <img class="th" id="" src="{{ STATIC_URL }}i/igra_logo.png" />
          </a><br><br>
        </div>
        <div class="large-3 columns">
          <a rel="nofollow" target="_blank" href="http://vk.com/club33796948">
            <img class="th" id="" src="{{ STATIC_URL }}i/an2_logo.png" />
          </a><br><br>
          <a rel="nofollow" target="_blank" href="http://algoritm35.ru">
            <img class="th" id="cmirit_logo" src="{{ STATIC_URL }}i/algo_logo.png" />
          </a><br><br>
          <a rel="nofollow" target="_blank" href="http://lingualeo.ru/">
            <img class="th" id="cmirit_logo" src="{{ STATIC_URL }}i/leo_logo.jpg" />
          </a><br><br>
        </div>
      </div>

    </div><!-- .panel -->
  </div><!-- .columns -->
</div><!-- .row -->


<div class="row">
  <div class="large-12 columns">
    <h3 class="text-center">Информационные партнеры</h3>
    <div class="panel">

      <div class="row">
        <div class="large-3 columns">
          <a rel="nofollow" target="_blank" href="http://smallbusiness.ru">
            <img class="th" id="" src="{{ STATIC_URL }}i/small_business_logo.png" />
          </a><br><br>
          <a rel="nofollow" target="_blank" href="http://startupafisha.ru">
            <img class="th" id="" src="{{ STATIC_URL }}i/rusbase_logo_.jpg" />
          </a><br><br>
          <a rel="nofollow" target="_blank" href="http://hackday.ru">
            <img class="th" id="" src="{{ STATIC_URL }}i/hackday_logo.png" />
          </a><br><br>
        </div>
        <div class="large-3 columns">
          <a rel="nofollow" target="_blank" href="http://invest35.ru" class="">
            <img class="th" id="corp_logo" src="{{ STATIC_URL }}i/corp_logo.png" />
          </a><br><br>
          <a rel="nofollow" target="_blank" href="http://risventures.com">
            <img class="th" id="risventures_logo" src="{{ STATIC_URL }}i/ris_ventures_logo_.png" />
          </a><br><br>
          <a rel="nofollow" target="_blank" href="http://www.it-start.pro/">
            <img class="th" id="" src="{{ STATIC_URL }}i/ros_logo.png" />
          </a><br><br>
        </div>
        <div class="large-3 columns">
          <a rel="nofollow" target="_blank" href="http://cio35.ru">
            <img class="th" id="itvologda_logo" src="{{ STATIC_URL }}i/itvologda_logo.png" />
          </a><br><br>
          <a rel="nofollow" target="_blank" href="http://geometria.ru">
            <img class="th" id="geometria_logo" src="{{ STATIC_URL }}i/geometria_logo.png" />
          </a><br><br>
        </div>
        <div class="large-3 columns">
          <a rel="nofollow" target="_blank" href="http://www.on-lineservice.ru/">
            <img class="th" id="" src="{{ STATIC_URL }}i/online_logo.jpg" />
          </a><br><br>
          <a rel="nofollow" target="_blank" href="http://adremamici.ru/">
            <img class="th" id="adrem_logo" src="{{ STATIC_URL }}i/adrem_logo.png" />
          </a><br><br>
          <a rel="nofollow" target="_blank" href="http://volbiz.ru/">
            <img class="th" id="volbiz_logo" src="{{ STATIC_URL }}i/volbiz_logo.gif" />
          </a><br><br>
        </div>
        <!--
        <div class="large-3 columns">
          <a rel="nofollow" target="_blank" href="http://synapse-studio.ru">
            <img class="th" id="synapse_logo" src="{{ STATIC_URL }}i/synapse_logo.png" />
          </a><br><br>
          <a rel="nofollow" target="_blank" href="http://tensor.ru">
            <img class="th" id="" src="{{ STATIC_URL }}i/tensor_logo.jpg" />
          </a><br><br>
          <a rel="nofollow" target="_blank" href="http://mallenom.ru">
            <img class="th" id="mallenom_logo" src="{{ STATIC_URL }}i/mallenom_logo.png" />
          </a>
        </div>
        -->
      </div>

    </div><!-- .panel -->
  </div><!-- .columns -->
</div><!-- .row -->