hackthon/apps/profiles/urls.py
#-*- coding: utf-8 -*-

from django.conf.urls import patterns, url

from profiles import views


urlpatterns = patterns('',
    url(r'^(?P<pk>\d+)/edit/$', views.ProfileEditView.as_view(),
                        name='profile_edit'),
    url(r'^list/$', views.ProifileList.as_view(),
                        name='profile_list'),
    url(r'^register/$', views.register,
                        name='profiles_register'),
    url(r'^register/sponsorship/$', views.sponsorship_register,
                        name='sponsorship_register'),
    url(r'^(?P<pk>\d+)/$', views.ProifileDetail.as_view(),
                        name='profile_detail'),

    url(r'^projects/list/$', views.ProjectList.as_view(),
                        name='project_list'),
    url(r'^projects/create/$', views.ProjectCreateView.as_view(),
                        name='project_create'),
    url(r'^projects/join/$', views.JoinProjectView.as_view(),
                        name='project_left'),
    url(r'^projects/left/$', views.LeftProjectView.as_view(),
                        name='project_join'),
    url(r'^projects/confirm/$', views.ConfirmRegisterView.as_view(),
                        name='project_confirm'),
    url(r'^projects/(?P<pk>\d+)/edit/$', views.ProjectEditView.as_view(),
                        name='project_edit'),
    url(r'^projects/(?P<pk>\d+)/$', views.ProjectDetail.as_view(),
                        name='project_detail'),
    url(r'^messages/$', views.messages_new,
                        name='messages'),
    url(r'^messages/zaebeezaebee/(?P<id>\d+)$', views.messages_zaebee,
                        name='messages_zaebee'),
)

hackthon/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.views.generic import TemplateView, RedirectView

from django.shortcuts import redirect
from django.contrib import admin
from django.contrib.auth import views as auth_views
admin.autodiscover()


urlpatterns = patterns('',
    (r'^admin/', include(admin.site.urls)),
)

#reg urls
urlpatterns += patterns('',
    url(r'^projects/$', RedirectView.as_view(url='/accounts/projects/list/')),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^password/change/$',
        auth_views.password_change,
        name='auth_password_change'),
    url(r'^password/change/done/$',
        auth_views.password_change_done,
        name='auth_password_change_done'),
    url(r'^password/reset/$',
        auth_views.password_reset,
        name='auth_password_reset'),
    url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.password_reset_confirm,
        name='auth_password_reset_confirm'),
    url(r'^password/reset/complete/$',
        auth_views.password_reset_complete,
        name='auth_password_reset_complete'),
    url(r'^password/reset/done/$',
        auth_views.password_reset_done,
        name='auth_password_reset_done'),
)

urlpatterns += patterns('',
    #(r'^$', TemplateView.as_view(template_name="default.html")),
    (r'^$', TemplateView.as_view(template_name="new.html")),
    (r'^first/$', TemplateView.as_view(template_name="first.html")),
    (r'^second/$', TemplateView.as_view(template_name="second.html")),
    (r'^accounts/', include('profiles.urls')),
    (r'^validate/', include('ajax_validation.urls')),
)

urlpatterns += (
    url(r'^static/(?P<path>.*)', 'django.views.static.serve', {'document_root':settings.STATIC_ROOT,'show_indexes': True}),
)

if settings.DEBUG:
    urlpatterns += (
        url(r'^static/(?P<path>.*)', 'django.views.static.serve', {'document_root':settings.STATIC_ROOT,'show_indexes': True}),
        url(r'^media/(?P<path>.*)', 'django.views.static.serve', {'document_root':settings.MEDIA_ROOT,'show_indexes': True}),
    )

hackthon/apps/profiles/models.py
# -*- coding: utf-8 -*-

from django.contrib.auth.models import User
from django.db import models

from django.utils.translation import ugettext_lazy as _


USER_ROLES = (
    ('programmer', u'Программист'),
    ('designer', u'Дизайнер'),
    ('manager', u'Менеджер'),
    ('student', u'Студент'),
    ('other', u'Другое'),
)


class SponsorProfile(models.Model):

    sponsor_email = models.EmailField(_('email'), max_length=75)

    def __unicode__(self):
        return self.sponsor_email


class UserProfile(models.Model):
    user = models.OneToOneField(User,
                        verbose_name=_('user'),
                        unique=True,
                        related_name='profile',)
    avatar = models.CharField(_('Avatar'), max_length=80,
                              blank=True, null=True)
    username = models.CharField(_('Username'), max_length=100)
    user_skills = models.TextField(_('User skills'))
    user_role = models.CharField(_('User role'), max_length=30,
                           choices=USER_ROLES)
    contact = models.CharField(_('Contact'), max_length=40, null=True)
    phone = models.CharField(_('Phone'), max_length=40, blank=True, null=True)
    has_idea = models.BooleanField(_('Has idea'), default=False)
    text_idea = models.TextField(_('Text idea'), blank=True, null=True)
    project = models.ForeignKey('UserProject', verbose_name=_('project'),
                               related_name=_('members'),
                               blank=True, null=True)
    confirmed = models.BooleanField('Confirmed', default=False)

    class Meta:
        verbose_name = _('Profile')
        verbose_name_plural = _('Profiles')

    def __unicode__(self):
        return self.user.username

    @property
    def in_team(self):
        try:
            team =  self.project or self.group
        except:
            return False
        if team:
            return True

    @property
    def team(self):
        if self.in_team:
            return self.project if self.project else self.group

    @property
    def empty(self):
        if self.username and self.user_skills and self.contact:
            return False
        return True

    @property
    def can_join(self):
        if not self.empty and not self.team:
            return True
        return False

    @property
    def can_left(self):
        if not self.empty and self.team.owner != self:
            return True
        return False

    @models.permalink
    def get_absolute_url(self):
        return ('profile_detail', None, {'pk':str(self.pk)})


class UserProject(models.Model):
    created = models.DateTimeField(_('Created'), auto_now=True)
    owner = models.OneToOneField(UserProfile,
                        verbose_name=_('owner'),
                        unique=True,
                        related_name='group',
                        blank=True,null=True,
                        default='')
    avatar = models.CharField(_('Avatar'), max_length=80,
                              blank=True, null=True)
    title = models.CharField(_('Title'), max_length=100)
    text_idea = models.TextField(_('Text idea'), blank=True, null=True)
    require = models.CharField(_('Require staff'), max_length=350, blank=True, null=True)
    is_full = models.BooleanField(_('Is full'), default=False)
    pirvate = models.BooleanField(_('Private'), default=False)
    archived = models.BooleanField(_('Archived'), default=False)

    class Meta:
        verbose_name = _('Project')
        verbose_name_plural = _('Projects')
        ordering = ('-created',)

    def __unicode__(self):
        return '%s - %s' % (self.owner, self.title)

    @models.permalink
    def get_absolute_url(self):
        return ('project_detail', None, {'pk':str(self.pk)})


class Message(models.Model):
    created = models.DateTimeField(_('Created'), auto_now=True)
    text = models.TextField(_('Message'))
    title = models.CharField(_('Title'), max_length=255, null=True, blank=True)

    class Meta:
        verbose_name = _('Message')
        verbose_name_plural = _('Messages')
        ordering = ('-created',)

    def __unicode__(self):
        if self.title:
            return u'%s' % self.title
        else:
            return ''


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profile, created = UserProfile.objects.get_or_create(user=instance)

models.signals.post_save.connect(create_user_profile, sender=User)

hackthon/apps/profiles/forms.py
#-*- coding: utf-8 -*-

from django import forms
from django.conf import settings
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from models import UserProfile, SponsorProfile, UserProject
from utils import clear_email


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        exclude = ('user', 'avatar') # User will be filled in by the view.


class UserProjectForm(forms.ModelForm):

    class Meta:
        model = UserProject
        exclude = ('owner', 'archived', 'avatar') # User will be filled in by the view.



# I put this on all required fields, because it's easier to pick up
# on them with CSS or JavaScript if they have a class of "required"
# in the HTML. Your mileage may vary. If/when Django ticket #3515
# lands in trunk, this will no longer be necessary.
attrs_dict = {'class': 'required'}


class RegistrationForm(forms.Form):
    """
    Form for registering a new user account.

    Validates that the requested username is not already in use, and
    requires the password to be entered twice to catch typos.

    Subclasses should feel free to add any additional validation they
    need, but should avoid defining a ``save()`` method -- the actual
    saving of collected user data is delegated to the active
    registration backend.

    """
    username = forms.RegexField(regex=r'^\w+$',
                                max_length=30,
                                widget=forms.TextInput(attrs=attrs_dict),
                                label=_("Username"),
                                error_messages={'invalid': _("This value must contain only letters, numbers and underscores.")})
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(attrs_dict,
                                                               max_length=75)),
                             label=_("Email address"))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs=attrs_dict, render_value=False),
                                label=_("Password"))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs=attrs_dict, render_value=False),
                                label=_("Password (again)"))

    def clean_username(self):
        """
        Validate that the username is alphanumeric and is not already
        in use.

        """
        try:
            user = User.objects.get(username__iexact=self.cleaned_data['username'])
        except User.DoesNotExist:
            return self.cleaned_data['username']
        raise forms.ValidationError(_("User with this username already exists."))

    def clean(self):
        """
        Verifiy that the values entered into the two password fields
        match. Note that an error here will end up in
        ``non_field_errors()`` because it doesn't apply to a single
        field.

        """
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(_("Password does not match."))
        return self.cleaned_data


class RegistrationFormUniqueEmail(forms.Form):
    """
    Subclass of ``RegistrationForm`` which enforces uniqueness of
    email addresses.

    """
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(attrs_dict,
                                                    maxlength=75)),
                                                    label=_("Email address"))
    password = forms.CharField(widget=forms.PasswordInput(attrs=attrs_dict, render_value=False),
                                label=_("Password"))

    def clean_email(self):
        """
        Validate that the supplied email address is unique for the
        site.

        """
        email = self.cleaned_data['email']
        if User.objects.filter(email__iexact=clear_email(email)).exists():
            raise forms.ValidationError(u"Такой email уже есть. Укажите, пожалуйста, другой адрес.")
        return email


class SponsorshipForm(forms.ModelForm):

    class Meta:
        model = SponsorProfile

    def clean_email(self):
        return email

hackthon/templates/hackpoint/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Hackpoint'13 Череповец</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
  	<link rel="stylesheet/less" type="text/css" href="less/bootstrap.less">
  	<link rel="stylesheet/less" type="text/css" href="less/responsive.less">
    <link rel="stylesheet/less" type="text/css" href="style.less">
    <script src="js/less-1.3.3.min.js" type="text/javascript"></script>
  	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
    <![endif]-->

  </head>

  <body>

    <div class="container">
    	<div class="row-fluid clearfix header">
        <div class="span4">
          <a href="/" class="logo"><h1 class="hidden">Hackpoint'13 Череповец</h1></a>
        </div>
        <div class="span8">
          <div class="social-place clearfix">
            <ul class="social pull-right">
                 <li class="vk">
                    <a href="http://vk.com/hackpoint" target="_blank">
                       <strong>ВКонтакте</strong>
                    </a>
                 </li>
                 <li class="twitter">
                    <a href="http://twitter.com/hackpoint_che" target="_blank">
                       <strong>Twitter</strong>
                    </a>
                 </li>
                 <li class="facebook">
                    <a href="http://facebook.com/hackpoint.che" target="_blank">
                      <strong>Facebook</strong>
                    </a>
                 </li>
              </ul>
            <span class="pull-right">Следи за обновлениями:</span>
          </div>
          <div class="nav-place clearfix">
              <ul class="nav nav-pills pull-right">
              <li class="active"><a href="#">О мероприятии</a></li>
              <li><a href="#">Спонсоры</a></li>
              <li><a href="#">Контакты</a></li>
            </ul>
          </div>
        </div>

      </div>
      <div class="jumbotron well">
        <div class="container-fluid">
          <div class="row-fluid">
            <div class="span12">
                      <h1>Точка превращения идеи в протип</h1>
                <p class="lead">Разработай проект, приложение или его прототип за 48 часов</p>
            </div>
          </div>
        </div>
      </div>
      
      <hr>


        <div class="row-fluid">
          <div class="span5" style="margin-bottom: 20px; padding-left: 40px;">
                <h4>Вас ожидает:</h6>
                  <ul>
                  <li>Много IT-специалистов</li>
                  <li>Бесплатное питание</li>
                  <li>48-часовой доступ на площадку</li>
                  <li>Море фана</li>
                  </ul>
                  <span>Участие бесплатно!</span>
                </div>
          <div class="span7 well registration" style="margin-bottom: 20px;">
            <h4>Регистрация на хакпоинт открыта</h4>
            <form id="register_simple" method="post" _lpchecked="1">

               <div class="input-append">
    <input type="text" id="id_email" name="email" placeholder="Введите ваш email">
    <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
  </div>
                
              </form>
          </div>
        </div>

  <hr>

  <div class="row-fluid time-and-place">
    <div class="span7">
        <div id="map" style="height:250px;"></div>
        <script src="http://api-maps.yandex.ru/2.0-stable/?load=package.standard&amp;lang=ru-RU" type="text/javascript"></script>
<script type="text/javascript">
  ymaps.ready(init);
  var myMap,
      placeMark;

  function init(){     
    myMap = new ymaps.Map ("map", {
      center: [59.122021, 37.931599],
      zoom: 16,
    });

    placeMark = new ymaps.Placemark([59.122021, 37.931599], {
      content: 'Череповец',
      balloonContent: 'Открытое творческое пространство &laquo;Простор&raquo;'
    });
    myMap.geoObjects.add(placeMark);
  }
</script>
    </div>
    <div class="span5">
        <h3 class="header"><i class="calendar-icon"></i>&nbsp;<span>Время</span></h3>
        <p><strong>19-21 апреля 2013 года</strong> <br>Начало: 18:00</p>

        <h3 class="header"><i class="globe-icon"></i>&nbsp;<span>Место</span></h3>
        <p>ул. Социалистическая 25, г. Череповец<br><b>Открытое творческое пространство «Простор»</b></p>
      </div>
    
  </div>

  <hr>

  <div class="row-fluid sponsors well">
    <h4>Наши спонсоры</h4>
    <div class="clearfix">
      <div class="sponsor-item">
        <a href="http://cmirit.ru/" target="_blank"><img src="{{ STATIC_URL }}img/sponsors/cmirit_logo.png" class="img-polaroid" /></a>
      </div>
      <div class="sponsor-item">
        <a href="http://cherepovets.interzet.ru/" target="_blank"><img src="{{ STATIC_URL }}img/sponsors/interzet_logo.png" class="img-polaroid" /></a>
      </div>
      <div class="sponsor-item">
        <a href="http://cheritclub.ru/" target="_blank"><img src="{{ STATIC_URL }}img/sponsors/cheritclub_logo.png" class="img-polaroid" /></a>
      </div>
      <div class="sponsor-item">
        <a href="http://synapse-studio.ru/" target="_blank"><img src="{{ STATIC_URL }}img/sponsors/synapse_logo.png" class="img-polaroid" /></a>
      </div>
    </div>
    <div class="clearfix">
      <div class="sponsor-item">
        <a href="http://imit.ru/" target="_blank"><img src="{{ STATIC_URL }}img/sponsors/imit_logo.png" class="img-polaroid" /></a>
      </div>
      <div class="sponsor-item">
        <a href="http://cio35.ru/" target="_blank"><img src="{{ STATIC_URL }}img/sponsors/itvologda_logo.png" class="img-polaroid" /></a>
      </div>
      <div class="sponsor-item">
        <a href="http://it-sobytie.ru/" target="_blank"><img src="{{ STATIC_URL }}img/sponsors/it-sobytie_logo.png" class="img-polaroid" /></a>
      </div>
      <div class="sponsor-item">
        <a href="http://volbiz.ru/" target="_blank"><img src="{{ STATIC_URL }}img/sponsors/volbiz_logo.png" class="img-polaroid" /></a>
      </div>
      <div class="sponsor-item">
        <a href="http://torgovorot.ru/" target="_blank"><img src="{{ STATIC_URL }}img/sponsors/torgovorot_logo.png" class="img-polaroid" /></a>
      </div>
    </div>
  </div>

  <div class="row-fluid">
    <h4 style="text-align:center;">Знаете как помочь ивенту или хотите быть спонсором? <a href="#sponsorship" class="btn btn-primary" data-toggle="modal">Наше предложение для партнеров</a></h4>
    
  </div>

      <hr>

      <div class="row-fluid footer">

        <div class="span4"><p>2013 &copy; HackPoint. Точка превращения идеи в прототип</p></div>
        <div class="span8">
<ul class="nav nav-pills pull-right">
              <li class="active"><a href="#">О мероприятии</a></li>
              <li><a href="#">Спонсоры</a></li>
              <li><a href="#">Контакты</a></li>
            </ul>
        </div>
      </div>

    	</div>

      <hr>
      <div class="row-fluid">
        <div class="span6">
            <!-- тут вставить ВК -->
        </div>
        <div class="span6">
            <!-- тут вставить Twitter -->
        </div>
      </div>

      
    </div>

<div id="sponsorship" class="modal hide fade">
    <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Хотите помочь мероприятию?</h3>
  </div>
  <div class="modal-body">
    <p>Мы отправим вам готовый пресс-релиз про hackpoint и спонсорское предложение, если вы оставите свой email</p>

      <form id="sponsorship_simple" action="/accounts/register/sponsorship/" method="post" style="text-align: center;">

                       <div class="input-append">
    <input type="text" id="id_sponsor_email" name="email" placeholder="Введите ваш email">
    <button type="submit" class="btn btn-primary">Отправить</button>
  </div>
      </form>
    <hr>
      <p>Или вы можете написать нам письмо с пометкой <b>"спонсорство"</b> на почту <a href="mailto:info@hackpoint.ru">info@hackpoint.ru</a></p>
  </div>
</div>


<div id="registerModal" class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Благодарим за регистрацию на hackpoint</h3>
  </div>
  <div class="modal-body">
    <p>Заполните форму и в дальнейшем вы сможете точнее подобрать команду и проект для участия.</p>
  <form method="POST" action="/accounts/register/" class="form-horizontal" id="register_full">
     <div class="control-group">
      <label class="control-label" for="username">Меня зовут</label>
      <div class="controls">
        <input id="id_username" type="text" name="username" value="" placeholder="Никнэйм или реальное имя">
      </div>
    </div>

    <div class="control-group">
      <label class="control-label" for="user_role">Моя роль в команде</label>
      <div class="controls">
        <select id="id_user_role" class="large" name="user_role">
          <option value="programmer">Программист</option>
          <option value="designer">Дизайнер</option>
          <option value="manager">Менеджер</option>
          <option value="student">Студент</option>
          <option value="other">Другое</option>
        </select>
      </div>
    </div>

    <div class="control-group">
      <div class="controls">
        <textarea rows="3" id="id_user_skills" name="user_skills" placeholder="Мои навыки, скилы, умения. Какими технологиями я обладаю."></textarea>
      </div>

    </div>

    <div class="control-group">
      <div class="controls"><label for="id_has_idea"><input type="checkbox" name="has_idea" id="id_has_idea"><span class="custom checkbox"></span> У меня есть идея для проекта</label></div>
      
    </div>

    <hr>

    <div class="control-group" style="text-align: center;">
      <input type="submit" class="btn btn-primary" value="Завершить">
    </div>
  </form>
  </div>
  
</div>
    <script src="js/bootstrap-modal.js" type="text/javascript"></script>
  </body>
</html>